// <auto-generated />
using CrmBot.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CrmBot.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171031111941_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrmBot.DataAccess.Models.TelegramChat", b =>
                {
                    b.Property<long>("ChatId");

                    b.Property<string>("AccessToken");

                    b.Property<Guid>("SecureKey")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UserId");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("TelegramChats");
                });

            modelBuilder.Entity("CrmBot.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CrmUserId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("TimeZone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrmBot.DataAccess.Models.TelegramChat", b =>
                {
                    b.HasOne("CrmBot.DataAccess.Models.User", "User")
                        .WithOne("Chat")
                        .HasForeignKey("CrmBot.DataAccess.Models.TelegramChat", "UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
